version: '3.9'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-certs:/certs
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-certs:
  mysql-data:
